version: '3'
services:
  macro-api:
    container_name: macro-api
    ports:
      - "8000:80"
      - "24:22"
      - "5000-5100:5000-5100"
      - "8001-8100:8001-8100"
    build:
      context: ./
      dockerfile: macroservice.dockerfile
    networks:
      - drpsnetwork
  # astro-ui:
  #   container_name: astro-ui
  #   build:
  #     context: ./
  #     dockerfile: astroui.dockerfile
  #   ports:
  #     - '3000:3000'
  #   networks:
  #     - drpsnetwork
networks:
  drpsnetwork:
    driver: bridge